import{a as m,S as h}from"./assets/vendor-4533621d.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const y="44503068-6cc3802f70205d42434a99aa5",g="https://pixabay.com/api/";async function d(t,r=1){return(await m.get(`${g}`,{params:{key:y,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}function f(t){const r=document.querySelector(".gallery"),s=t.map(({webformatURL:e,largeImageURL:o,tags:a})=>`
    <div class="photo-card">
      <a class="gallery__item" href="${o}">
        <img class="gallery__image" src="${e}" alt="${a}" />
      </a>
      <div class="info">
        <p class="info-item">${a}</p>
      </div>
    </div>`).join("");r.insertAdjacentHTML("beforeend",s),new h(".gallery a").refresh()}function p(){document.querySelector(".gallery").innerHTML=""}function u(t){document.querySelector("#load-more").classList.toggle("hidden",!t)}const L=document.querySelector(".search-form"),S=document.querySelector("#load-more"),b=document.querySelector(".gallery");let c="",n=1,i=0;L.addEventListener("submit",v);S.addEventListener("click",M);async function v(t){if(t.preventDefault(),c=t.currentTarget.elements.searchQuery.value.trim(),n=1,p(),u(!1),c!=="")try{const r=await d(c,n);i=r.totalHits,i>0?(f(r.hits),u(n<Math.ceil(i/15))):alert("No images found.")}catch(r){console.error(r)}}async function M(){n+=1;try{const t=await d(c,n);f(t.hits),n>=Math.ceil(i/15)&&(u(!1),alert("We're sorry, but you've reached the end of search results."))}catch(t){console.error(t)}q()}function q(){const{height:t}=b.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
